name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip Project
        run: unzip G8Raid.zip

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}   # 新增这行
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: G8Raid
          targetPlatform: Android
          versioning: None

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: G8Raid-APK
          path: build/Android/*.apk   # 改成了只抓取apk文件
