name: 申请许可证
on: workflow_dispatch
jobs:
  get-alf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: game-ci/unity-request-activation-file@v2
        id: getALF
        with:
          unityVersion: 2022.3.10f1
      - name: 打印
        run: cat ${{ steps.getALF.outputs.filePath }} | base64
